name: crypto_data_factory
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=23.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - websockets=9.1
  - aiohttp>=3.8.0
  - python-dotenv>=1.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - pip:
    - python-binance>=1.0.19
    - ccxt>=4.0.0
    - ta>=0.10.0
    - tqdm>=4.65.0
    - hurry.filesize>=0.9
    - requests>=2.28.0
